### PR TITLE
use ssh args for getting connection settings

### PR DESCRIPTION
**Pull request by mibmo**
fixes args such as `--ssh-port` not affecting the whole program (specifically the keyscan porting was impacting my setup)

tests seem to pass ｏｋ

### CODE REVIEW

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify queue

**Comment by mibmo** [comment]
> @mergify queue

I'm guessing this means it's getting merged, but is there a general eta? not at all important, just curious whether it's on the order of days, weeks, or months. To me this is a bug that makes nixos-anywhere literally unusable and I don't think my setup is _too_ non-standard, just a different ssh port.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
> > @mergify queue
> 
> I'm guessing this means it's getting merged, but is there a general eta? not at all important, just curious whether it's on the order of days, weeks, or months. To me this is a bug that makes nixos-anywhere literally unusable and I don't think my setup is _too_ non-standard, just a different ssh port.

Should be instant, but I had to re-enable it after migrating from numtide to the nix-community org.

**Comment by mibmo** [comment]
> > > @mergify queue
> > 
> > 
> > I'm guessing this means it's getting merged, but is there a general eta? not at all important, just curious whether it's on the order of days, weeks, or months. To me this is a bug that makes nixos-anywhere literally unusable and I don't think my setup is _too_ non-standard, just a different ssh port.
> 
> Should be instant, but I had to re-enable it after migrating from numtide to the nix-community org.

Ahh, gotcha; no worries :) thanks for merging.

**Pull request merged**
