### PR TITLE
Adapt nixos-anywhere to work with a remote running alpine

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
Converted to draft, the copying of authorized_keys should instead be fixed by supporting DOAS_USER in the kexec images

**Comment by shlevy** [comment]
https://github.com/nix-community/nixos-images/pull/184 adds proper doas support to the kexec images

**Review by Lassulus — APPROVED** [review]
looks good, haven't tested anything with those changes.

**Comment by shlevy** [comment]
I’ve tested this on a local Alpine VM (alongside https://github.com/nix-community/nixos-images/pull/184)

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
