### PR TITLE
feat(src/nixos-anywhere): use tar and ssh instead of rsync

### LINKED ISSUE #260: rsync command not found with 23.11 nixos image
nixos-anywhere fails at copy extra file step using as installation target a machine booted with nixos 23.11 minimal iso image: 
https://channels.nixos.org/nixos-23.11/latest-nixos-minimal-x86_64-linux.iso

nixos-anywhere command:
nix run github:numtide/nixos-anywhere -- --extra-files "$temp" --flake .#server02 root@$192.168.178.191

This is the error:

```nix
+ echo '### Copying extra files ###'
### Copying extra files ###
+ rsync -rlpv -FF -e 'ssh -i "/tmp/tmp.eYUCcg96wX"/nixos-anywhere -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' /tmp/tmp.Ol4VOcuUb6/ root@192.168.178.191:/mnt/
Warning: Permanently added '192.168.178.191' (ED25519) to the list of known hosts.
bash: line 1: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.2.7]
+ rm -rf /tmp/tmp.eYUCcg96wX
``` 
Using the 23.05 image installation works without any issue.

### PR DESCRIPTION
**Pull request by Prince213**
Resolves #260. Closes #295.

This PR replaces use of rsync with a combination of tar and ssh. It's an alternative solution to #295, but it avoid the problem as per https://github.com/nix-community/nixos-anywhere/pull/295#discussion_r1540782391. Also, directly copying with scp will not preserve symbolic links, which isn't a issue with this PR.

One notable change is that `extra_files` is assumed to be a directory, though there doesn't seem to be much case for it to be (multiple) files (checked within the repo), which isn't useful anyway because the exact path can't be easily specified (see also #283).

### CODE REVIEW

**Comment by Prince213** [comment]
@Mic92 please take a look.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergifyio rebase

**Comment by Prince213** [comment]
Sorry for that @Mic92, authorized now. Please try again, it should now work.

**Pull request closed without merging**
